### ISSUE TITLE
SetRecords appears to delete existing records

### ISSUE THREAD

**Issue by anderspitman** [libdns/namecheap#1]
Hey, thanks for implementing a Namecheap integration!

When trying it out, I noticed that any existing records that aren't included when calling `SetRecords` appear to be deleted. I'm not very familiar with `libdns`, but is that expected behavior? The Cloudflare integration doesn't seem to work this way. And my understanding of this:

https://github.com/libdns/libdns/blob/75d1f505ee7f0faee2fd02953faadf69d5eaf870/libdns.go#L64

Is that existing records should be preserved.

Thanks again!

**Comment by nrfox** [comment]
Thanks for kicking the tires!

I believe you're right and the implementation should be updated to match the spec you linked. `SetRecords` should be a "create or update" operation whereas I had initially interpreted it to be a "replace" operation. Maybe @mholt can confirm? And then I'm happy to work on a patch or review one if you'd like to submit one.

**Comment by mholt** [comment]
Yeah, so it's like a "create or update" in that when the function returns, the inputs are now present in the zone, even if that means replacing existing records with the same name so that they match the inputs. It shouldn't, however, obliterate any other records that aren't described in the input. It should only affect records that are present in the input.

**Comment by nrfox** [comment]
@anderspitman This patch should fix the issue if you would like to test it out: https://github.com/libdns/namecheap/pull/2
